query FetchWizards {
  wizards {
    name
    level
    race
    job
    spells {
      name
      attack
      range
    }
  }
}

query FetchSpecificWizardQuery {
  wizard(id: "1") {
    name
  }
}

# Pass data in Query Variables
query FetchSomeWizard($wizardId: ID!) {
  wizard(id: $wizardId) {
    id
    name
  }
}

query FetchAllCharacters {
  characters {
    ... on Fighter {
      id
      name
    }
    ... on Wizard {
      id
      name
    }
  }
}

mutation AddCharacter($input: CharacterInput!) {
  addCharacter(input: $input) {
    __typename
    ... on Fighter {
      id
      name
      race
      weapon {
        name
      }
    }
    ... on Wizard {
      id
      name
      race
      spells {
        name
      }
    }
  }
}
